apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lwargocd
  name: lwargocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwargocd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lwargocd
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
