apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lw
    app.kubernetes.io/instance: argocdfile1
  name: lw
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lw
  type: LoadBalancer
status:
  loadBalancer: {}
