apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lw
  name: lw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lw
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
